import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils"
import "./globals.css";
import Navbar from "@/components/custom/nav";

const fontSans = FontSans({
  subsets: ["latin-ext"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Victreat | Treat you Cancer with Victory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <head>
        <link rel="icon" href="/images/fav.svg" sizes="any" />

      </head>
      <body className={cn(
        " antialiased flex-col items-center justify-center m-0",
        fontSans.variable,
        fontSans.className
      )}>

        <Navbar />
        {children}
      </body>
    </html>
  );
}
